version: '3'

services:

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=debug
      - POSTGRES_PASSWORD=debug
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data


#  userservice:
#    container_name: user_service
#    image: user_service
#    restart: on-failure
#    expose:
#      - 8091
#    ports:
#      - 8091:8091
#    depends_on:
#      - db

  web-app:
    container_name: web-app
    image: web-app
    ports:
      - 3000:3000
    stdin_open:
      true

volumes:
  db:
    driver: local