version: '3'

services:

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=debug
      - POSTGRES_PASSWORD=debug
      - POSTGRES_DATABASE=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data


  user_service:
    container_name: user_service
    image: user_service
    restart: on-failure
    environment:
      HOST_IP: $HOST_IP
    expose:
      - 8091
    ports:
      - 8091:8091
    depends_on:
      - db

  web-app:
    container_name: web-app
    image: web-app
    environment:
      REACT_APP_HOST_IP: $REACT_APP_HOST_IP
    ports:
      - 3000:3000
    stdin_open:
      true
    depends_on:
      - db
      - user_service

volumes:
  db: