spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      username: msalihovic3
      password: m1234
  datasource:
    url: 'jdbc:postgresql://localhost:54328/user_db'
    username: 'postgres'
    password: 'root'
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: mklinika22@gmail.com
    password: vwezaavfnajuzade
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#    regisret:
#  instance:
#    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8091
#grpc:
#  server:
#    port: 9093