spring:
  application:
    name: userservice
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      username: msalihovic3
      password: m1234
  datasource:
    url: 'jdbc:postgresql://db:5432/postgres'
    username: 'debug'
    password: 'debug'
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

#  mail:
##    default-encoding: UTF-8
#    host: smtp.gmail.com
#    username: mklinika22@gmail.com
#    password: vwezaavfnajuzade
#    port: 587
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#    smtp:
#      ssl:
#        protocols: TLSv1.2
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#    regisret:
#  instance:
#    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8091
#grpc:
#  server:
#    port: 9093